"""
Authoritative Reference Datasets for Indian Election Simulation Platform.
Sources:
- Election Commission of India (ECI): https://eci.gov.in
- Delimitation of Parliamentary and Assembly Constituencies Order
- Form 7A Public Candidate Nominations and Affidavits
Note: All voting in this platform is an academic demonstration and has no legal standing.
"""

INDIAN_STATES = [
    {"name": "Andaman and Nicobar Islands", "code": "AN", "is_ut": True, "assembly": 0, "parliamentary": 1},
    {"name": "Andhra Pradesh", "code": "AP", "is_ut": False, "assembly": 175, "parliamentary": 25},
    {"name": "Arunachal Pradesh", "code": "AR", "is_ut": False, "assembly": 60, "parliamentary": 2},
    {"name": "Assam", "code": "AS", "is_ut": False, "assembly": 126, "parliamentary": 14},
    {"name": "Bihar", "code": "BR", "is_ut": False, "assembly": 243, "parliamentary": 40},
    {"name": "Chandigarh", "code": "CH", "is_ut": True, "assembly": 0, "parliamentary": 1},
    {"name": "Chhattisgarh", "code": "CG", "is_ut": False, "assembly": 90, "parliamentary": 11},
    {"name": "Dadra and Nagar Haveli and Daman and Diu", "code": "DH", "is_ut": True, "assembly": 0, "parliamentary": 2},
    {"name": "Delhi (NCT)", "code": "DL", "is_ut": True, "assembly": 70, "parliamentary": 7},
    {"name": "Goa", "code": "GA", "is_ut": False, "assembly": 40, "parliamentary": 2},
    {"name": "Gujarat", "code": "GJ", "is_ut": False, "assembly": 182, "parliamentary": 26},
    {"name": "Haryana", "code": "HR", "is_ut": False, "assembly": 90, "parliamentary": 10},
    {"name": "Himachal Pradesh", "code": "HP", "is_ut": False, "assembly": 68, "parliamentary": 4},
    {"name": "Jammu and Kashmir", "code": "JK", "is_ut": True, "assembly": 90, "parliamentary": 5},
    {"name": "Jharkhand", "code": "JH", "is_ut": False, "assembly": 81, "parliamentary": 14},
    {"name": "Karnataka", "code": "KA", "is_ut": False, "assembly": 224, "parliamentary": 28},
    {"name": "Kerala", "code": "KL", "is_ut": False, "assembly": 140, "parliamentary": 20},
    {"name": "Ladakh", "code": "LA", "is_ut": True, "assembly": 0, "parliamentary": 1},
    {"name": "Lakshadweep", "code": "LD", "is_ut": True, "assembly": 0, "parliamentary": 1},
    {"name": "Madhya Pradesh", "code": "MP", "is_ut": False, "assembly": 230, "parliamentary": 29},
    {"name": "Maharashtra", "code": "MH", "is_ut": False, "assembly": 288, "parliamentary": 48},
    {"name": "Manipur", "code": "MN", "is_ut": False, "assembly": 60, "parliamentary": 2},
    {"name": "Meghalaya", "code": "ML", "is_ut": False, "assembly": 60, "parliamentary": 2},
    {"name": "Mizoram", "code": "MZ", "is_ut": False, "assembly": 40, "parliamentary": 1},
    {"name": "Nagaland", "code": "NL", "is_ut": False, "assembly": 60, "parliamentary": 1},
    {"name": "Odisha", "code": "OD", "is_ut": False, "assembly": 147, "parliamentary": 21},
    {"name": "Puducherry", "code": "PY", "is_ut": True, "assembly": 30, "parliamentary": 1},
    {"name": "Punjab", "code": "PB", "is_ut": False, "assembly": 117, "parliamentary": 13},
    {"name": "Rajasthan", "code": "RJ", "is_ut": False, "assembly": 200, "parliamentary": 25},
    {"name": "Sikkim", "code": "SK", "is_ut": False, "assembly": 32, "parliamentary": 1},
    {"name": "Tamil Nadu", "code": "TN", "is_ut": False, "assembly": 234, "parliamentary": 39},
    {"name": "Telangana", "code": "TS", "is_ut": False, "assembly": 119, "parliamentary": 17},
    {"name": "Tripura", "code": "TR", "is_ut": False, "assembly": 60, "parliamentary": 2},
    {"name": "Uttar Pradesh", "code": "UP", "is_ut": False, "assembly": 403, "parliamentary": 80},
    {"name": "Uttarakhand", "code": "UK", "is_ut": False, "assembly": 70, "parliamentary": 5},
    {"name": "West Bengal", "code": "WB", "is_ut": False, "assembly": 294, "parliamentary": 42},
]

TN_DISTRICTS = [
    "Ariyalur", "Chengalpattu", "Chennai", "Coimbatore", "Cuddalore",
    "Dharmapuri", "Dindigul", "Erode", "Kallakurichi", "Kancheepuram",
    "Kanniyakumari", "Karur", "Krishnagiri", "Madurai", "Mayiladuthurai",
    "Nagapattinam", "Namakkal", "Nilgiris", "Perambalur", "Pudukkottai",
    "Ramanathapuram", "Ranipet", "Salem", "Sivaganga", "Tenkasi",
    "Thanjavur", "Theni", "Thoothukkudi", "Tiruchirappalli", "Tirunelveli",
    "Tirupathur", "Tiruppur", "Thiruvallur", "Tiruvannamalai", "Tiruvarur",
    "Vellore", "Viluppuram", "Virudhunagar"
]

# Official 234 Assembly Constituencies of Tamil Nadu (Numbers 1 to 234)
TN_ASSEMBLY_CONSTITUENCIES = [
    # Thiruvallur
    (1, "Gummidipoondi", "Thiruvallur", "GEN"),
    (2, "Ponneri", "Thiruvallur", "SC"),
    (3, "Tiruttani", "Thiruvallur", "GEN"),
    (4, "Thiruvallur", "Thiruvallur", "GEN"),
    (5, "Poonamallee", "Thiruvallur", "SC"),
    (6, "Avadi", "Thiruvallur", "GEN"),
    (7, "Maduravoyal", "Thiruvallur", "GEN"),
    (8, "Ambattur", "Thiruvallur", "GEN"),
    (9, "Madavaram", "Thiruvallur", "GEN"),
    (10, "Thiruvottiyur", "Thiruvallur", "GEN"),
    # Chennai
    (11, "Dr. Radhakrishnan Nagar", "Chennai", "GEN"),
    (12, "Perambur", "Chennai", "GEN"),
    (13, "Kolathur", "Chennai", "GEN"),
    (14, "Villivakkam", "Chennai", "GEN"),
    (15, "Thiru-Vi-Ka-Nagar", "Chennai", "SC"),
    (16, "Egmore", "Chennai", "SC"),
    (17, "Royapuram", "Chennai", "GEN"),
    (18, "Harbour", "Chennai", "GEN"),
    (19, "Chepauk-Thiruvallikeni", "Chennai", "GEN"),
    (20, "Thousand Lights", "Chennai", "GEN"),
    (21, "Anna Nagar", "Chennai", "GEN"),
    (22, "Virugampakkam", "Chennai", "GEN"),
    (23, "Saidapet", "Chennai", "GEN"),
    (24, "Thiyagarayanagar", "Chennai", "GEN"),
    (25, "Mylapore", "Chennai", "GEN"),
    (26, "Velachery", "Chennai", "GEN"),
    # Chengalpattu & Kancheepuram
    (27, "Shozhinganallur", "Chengalpattu", "GEN"),
    (28, "Alandur", "Chengalpattu", "GEN"),
    (29, "Sriperumbudur", "Kancheepuram", "SC"),
    (30, "Pallavaram", "Chengalpattu", "GEN"),
    (31, "Tambaram", "Chengalpattu", "GEN"),
    (32, "Chengalpattu", "Chengalpattu", "GEN"),
    (33, "Thiruporur", "Chengalpattu", "GEN"),
    (34, "Cheyyur", "Chengalpattu", "SC"),
    (35, "Maduranthakam", "Chengalpattu", "SC"),
    (36, "Uthiramerur", "Kancheepuram", "GEN"),
    (37, "Kancheepuram", "Kancheepuram", "GEN"),
    # Ranipet, Vellore, Tirupathur
    (38, "Arakkonam", "Ranipet", "SC"),
    (39, "Sholingur", "Ranipet", "GEN"),
    (40, "Katpadi", "Vellore", "GEN"),
    (41, "Ranipet", "Ranipet", "GEN"),
    (42, "Arcot", "Ranipet", "GEN"),
    (43, "Vellore", "Vellore", "GEN"),
    (44, "Anaikattu", "Vellore", "GEN"),
    (45, "Kilvaithinankuppam", "Vellore", "SC"),
    (46, "Gudiyattam", "Vellore", "SC"),
    (47, "Vaniyambadi", "Tirupathur", "GEN"),
    (48, "Ambur", "Tirupathur", "GEN"),
    (49, "Jolarpet", "Tirupathur", "GEN"),
    (50, "Tirupattur", "Tirupathur", "GEN"),
    # Krishnagiri & Dharmapuri
    (51, "Uthangarai", "Krishnagiri", "SC"),
    (52, "Bargur", "Krishnagiri", "GEN"),
    (53, "Krishnagiri", "Krishnagiri", "GEN"),
    (54, "Veppanahalli", "Krishnagiri", "GEN"),
    (55, "Hosur", "Krishnagiri", "GEN"),
    (56, "Thalli", "Krishnagiri", "GEN"),
    (57, "Palacode", "Dharmapuri", "GEN"),
    (58, "Pennagaram", "Dharmapuri", "GEN"),
    (59, "Dharmapuri", "Dharmapuri", "GEN"),
    (60, "Pappireddippatti", "Dharmapuri", "GEN"),
    (61, "Harur", "Dharmapuri", "SC"),
    # Tiruvannamalai
    (62, "Chengam", "Tiruvannamalai", "SC"),
    (63, "Tiruvannamalai", "Tiruvannamalai", "GEN"),
    (64, "Kilpennathur", "Tiruvannamalai", "GEN"),
    (65, "Kalasapakkam", "Tiruvannamalai", "GEN"),
    (66, "Polur", "Tiruvannamalai", "GEN"),
    (67, "Arani", "Tiruvannamalai", "GEN"),
    (68, "Cheyyar", "Tiruvannamalai", "GEN"),
    (69, "Vandavasi", "Tiruvannamalai", "SC"),
    # Viluppuram & Kallakurichi
    (70, "Gingee", "Viluppuram", "GEN"),
    (71, "Mailam", "Viluppuram", "GEN"),
    (72, "Tindivanam", "Viluppuram", "SC"),
    (73, "Vanur", "Viluppuram", "SC"),
    (74, "Viluppuram", "Viluppuram", "GEN"),
    (75, "Vikravandi", "Viluppuram", "GEN"),
    (76, "Tirukkoyilur", "Viluppuram", "GEN"),
    (77, "Ulundurpettai", "Kallakurichi", "GEN"),
    (78, "Rishivandiyam", "Kallakurichi", "GEN"),
    (79, "Sankarapuram", "Kallakurichi", "GEN"),
    (80, "Kallakurichi", "Kallakurichi", "SC"),
    # Salem
    (81, "Gangavalli", "Salem", "SC"),
    (82, "Attur", "Salem", "SC"),
    (83, "Yercaud", "Salem", "ST"),
    (84, "Omalur", "Salem", "GEN"),
    (85, "Mettur", "Salem", "GEN"),
    (86, "Edappadi", "Salem", "GEN"),
    (87, "Sankari", "Salem", "GEN"),
    (88, "Salem (West)", "Salem", "GEN"),
    (89, "Salem (North)", "Salem", "GEN"),
    (90, "Salem (South)", "Salem", "GEN"),
    (91, "Veerapandi", "Salem", "GEN"),
    # Namakkal
    (92, "Rasipuram", "Namakkal", "SC"),
    (93, "Senthamangalam", "Namakkal", "ST"),
    (94, "Namakkal", "Namakkal", "GEN"),
    (95, "Paramathi-Velur", "Namakkal", "GEN"),
    (96, "Tiruchengodu", "Namakkal", "GEN"),
    (97, "Kumarapalayam", "Namakkal", "GEN"),
    # Erode & Tiruppur
    (98, "Erode (East)", "Erode", "GEN"),
    (99, "Erode (West)", "Erode", "GEN"),
    (100, "Modakkurichi", "Erode", "GEN"),
    (101, "Dharapuram", "Tiruppur", "SC"),
    (102, "Kangayam", "Tiruppur", "GEN"),
    (103, "Perundurai", "Erode", "GEN"),
    (104, "Bhavani", "Erode", "GEN"),
    (105, "Anthiyur", "Erode", "GEN"),
    (106, "Gobichettipalayam", "Erode", "GEN"),
    (107, "Bhavanisagar", "Erode", "SC"),
    # Nilgiris
    (108, "Udhagamandalam", "Nilgiris", "GEN"),
    (109, "Gudalur", "Nilgiris", "SC"),
    (110, "Coonoor", "Nilgiris", "GEN"),
    # Coimbatore & Tiruppur
    (111, "Mettupalayam", "Coimbatore", "GEN"),
    (112, "Avanashi", "Tiruppur", "SC"),
    (113, "Tiruppur (North)", "Tiruppur", "GEN"),
    (114, "Tiruppur (South)", "Tiruppur", "GEN"),
    (115, "Palladam", "Tiruppur", "GEN"),
    (116, "Sulur", "Coimbatore", "GEN"),
    (117, "Kavundampalayam", "Coimbatore", "GEN"),
    (118, "Coimbatore (North)", "Coimbatore", "GEN"),
    (119, "Thondamuthur", "Coimbatore", "GEN"),
    (120, "Coimbatore (South)", "Coimbatore", "GEN"),
    (121, "Singanallur", "Coimbatore", "GEN"),
    (122, "Kinathukadavu", "Coimbatore", "GEN"),
    (123, "Pollachi", "Coimbatore", "GEN"),
    (124, "Valparai", "Coimbatore", "SC"),
    (125, "Udumalaipettai", "Tiruppur", "GEN"),
    (126, "Madathukulam", "Tiruppur", "GEN"),
    # Dindigul
    (127, "Palani", "Dindigul", "GEN"),
    (128, "Oddanchatram", "Dindigul", "GEN"),
    (129, "Athoor", "Dindigul", "GEN"),
    (130, "Nilakkottai", "Dindigul", "SC"),
    (131, "Natham", "Dindigul", "GEN"),
    (132, "Dindigul", "Dindigul", "GEN"),
    (133, "Vedasandur", "Dindigul", "GEN"),
    # Karur
    (134, "Aravakurichi", "Karur", "GEN"),
    (135, "Karur", "Karur", "GEN"),
    (136, "Krishnarayapuram", "Karur", "SC"),
    (137, "Kulithalai", "Karur", "GEN"),
    # Tiruchirappalli
    (138, "Manapparai", "Tiruchirappalli", "GEN"),
    (139, "Srirangam", "Tiruchirappalli", "GEN"),
    (140, "Tiruchirappalli (West)", "Tiruchirappalli", "GEN"),
    (141, "Tiruchirappalli (East)", "Tiruchirappalli", "GEN"),
    (142, "Thiruverumbur", "Tiruchirappalli", "GEN"),
    (143, "Lalgudi", "Tiruchirappalli", "GEN"),
    (144, "Manachanallur", "Tiruchirappalli", "GEN"),
    (145, "Musiri", "Tiruchirappalli", "GEN"),
    (146, "Thuraiyur", "Tiruchirappalli", "SC"),
    # Perambalur & Ariyalur
    (147, "Perambalur", "Perambalur", "SC"),
    (148, "Kunnam", "Ariyalur", "GEN"),
    (149, "Ariyalur", "Ariyalur", "GEN"),
    (150, "Jayankondam", "Ariyalur", "GEN"),
    # Cuddalore
    (151, "Tittakudi", "Cuddalore", "SC"),
    (152, "Vriddhachalam", "Cuddalore", "GEN"),
    (153, "Neyveli", "Cuddalore", "GEN"),
    (154, "Panruti", "Cuddalore", "GEN"),
    (155, "Cuddalore", "Cuddalore", "GEN"),
    (156, "Kurinjipadi", "Cuddalore", "GEN"),
    (157, "Bhuvanagiri", "Cuddalore", "GEN"),
    (158, "Chidambaram", "Cuddalore", "GEN"),
    (159, "Kattumannarkoil", "Cuddalore", "SC"),
    # Mayiladuthurai & Nagapattinam
    (160, "Sirkazhi", "Mayiladuthurai", "SC"),
    (161, "Mayiladuthurai", "Mayiladuthurai", "GEN"),
    (162, "Poompuhar", "Mayiladuthurai", "GEN"),
    (163, "Nagapattinam", "Nagapattinam", "GEN"),
    (164, "Kilvelur", "Nagapattinam", "SC"),
    (165, "Vedaranyam", "Nagapattinam", "GEN"),
    # Tiruvarur
    (166, "Thiruthuraipoondi", "Tiruvarur", "SC"),
    (167, "Mannargudi", "Tiruvarur", "GEN"),
    (168, "Thiruvarur", "Tiruvarur", "GEN"),
    (169, "Nannilam", "Tiruvarur", "GEN"),
    # Thanjavur
    (170, "Thiruvidaimarudur", "Thanjavur", "SC"),
    (171, "Kumbakonam", "Thanjavur", "GEN"),
    (172, "Papanasam", "Thanjavur", "GEN"),
    (173, "Thiruvaiyaru", "Thanjavur", "GEN"),
    (174, "Thanjavur", "Thanjavur", "GEN"),
    (175, "Orathanadu", "Thanjavur", "GEN"),
    (176, "Pattukkottai", "Thanjavur", "GEN"),
    (177, "Peravurani", "Thanjavur", "GEN"),
    # Pudukkottai
    (178, "Gandarvakottai", "Pudukkottai", "SC"),
    (179, "Viralimalai", "Pudukkottai", "GEN"),
    (180, "Pudukkottai", "Pudukkottai", "GEN"),
    (181, "Thirumayam", "Pudukkottai", "GEN"),
    (182, "Alangudi", "Pudukkottai", "GEN"),
    (183, "Aranthangi", "Pudukkottai", "GEN"),
    # Sivaganga
    (184, "Karaikudi", "Sivaganga", "GEN"),
    (185, "Tiruppattur", "Sivaganga", "GEN"),
    (186, "Sivaganga", "Sivaganga", "GEN"),
    (187, "Manamadurai", "Sivaganga", "SC"),
    # Madurai
    (188, "Melur", "Madurai", "GEN"),
    (189, "Madurai East", "Madurai", "GEN"),
    (190, "Sholavandan", "Madurai", "SC"),
    (191, "Madurai North", "Madurai", "GEN"),
    (192, "Madurai South", "Madurai", "GEN"),
    (193, "Madurai Central", "Madurai", "GEN"),
    (194, "Madurai West", "Madurai", "GEN"),
    (195, "Thiruparankundram", "Madurai", "GEN"),
    (196, "Thirumangalam", "Madurai", "GEN"),
    (197, "Usilampatti", "Madurai", "GEN"),
    # Theni
    (198, "Andipatti", "Theni", "GEN"),
    (199, "Periyakulam", "Theni", "SC"),
    (200, "Bodinayakanur", "Theni", "GEN"),
    (201, "Cumbum", "Theni", "GEN"),
    # Virudhunagar
    (202, "Rajapalayam", "Virudhunagar", "GEN"),
    (203, "Srivilliputhur", "Virudhunagar", "SC"),
    (204, "Sattur", "Virudhunagar", "GEN"),
    (205, "Sivakasi", "Virudhunagar", "GEN"),
    (206, "Virudhunagar", "Virudhunagar", "GEN"),
    (207, "Aruppukkottai", "Virudhunagar", "GEN"),
    (208, "Tiruchuli", "Virudhunagar", "GEN"),
    # Ramanathapuram
    (209, "Paramakudi", "Ramanathapuram", "SC"),
    (210, "Tiruvadanai", "Ramanathapuram", "GEN"),
    (211, "Ramanathapuram", "Ramanathapuram", "GEN"),
    (212, "Mudukulathur", "Ramanathapuram", "GEN"),
    # Thoothukkudi
    (213, "Vilathikulam", "Thoothukkudi", "GEN"),
    (214, "Thoothukkudi", "Thoothukkudi", "GEN"),
    (215, "Tiruchendur", "Thoothukkudi", "GEN"),
    (216, "Srivaikuntam", "Thoothukkudi", "GEN"),
    (217, "Ottapidaram", "Thoothukkudi", "SC"),
    (218, "Kovilpatti", "Thoothukkudi", "GEN"),
    # Tenkasi & Tirunelveli
    (219, "Sankarankovil", "Tenkasi", "SC"),
    (220, "Vasudevanallur", "Tenkasi", "SC"),
    (221, "Kadayanallur", "Tenkasi", "GEN"),
    (222, "Tenkasi", "Tenkasi", "GEN"),
    (223, "Alangulam", "Tenkasi", "GEN"),
    (224, "Tirunelveli", "Tirunelveli", "GEN"),
    (225, "Ambasamudram", "Tirunelveli", "GEN"),
    (226, "Palayamkottai", "Tirunelveli", "GEN"),
    (227, "Nanguneri", "Tirunelveli", "GEN"),
    (228, "Radhapuram", "Tirunelveli", "GEN"),
    # Kanniyakumari
    (229, "Kanniyakumari", "Kanniyakumari", "GEN"),
    (230, "Nagercoil", "Kanniyakumari", "GEN"),
    (231, "Colachel", "Kanniyakumari", "GEN"),
    (232, "Padmanabhapuram", "Kanniyakumari", "GEN"),
    (233, "Vilavancode", "Kanniyakumari", "GEN"),
    (234, "Killiyoor", "Kanniyakumari", "GEN"),
]

# All 39 Parliamentary Constituencies in Tamil Nadu + Key National Constituencies
PARLIAMENTARY_CONSTITUENCIES = [
    # Tamil Nadu (39)
    (1, "Thiruvallur", "Tamil Nadu", "SC"),
    (2, "Chennai North", "Tamil Nadu", "GEN"),
    (3, "Chennai South", "Tamil Nadu", "GEN"),
    (4, "Chennai Central", "Tamil Nadu", "GEN"),
    (5, "Sriperumbudur", "Tamil Nadu", "GEN"),
    (6, "Kancheepuram", "Tamil Nadu", "SC"),
    (7, "Arakkonam", "Tamil Nadu", "GEN"),
    (8, "Vellore", "Tamil Nadu", "GEN"),
    (9, "Krishnagiri", "Tamil Nadu", "GEN"),
    (10, "Dharmapuri", "Tamil Nadu", "GEN"),
    (11, "Tiruvannamalai", "Tamil Nadu", "GEN"),
    (12, "Arani", "Tamil Nadu", "GEN"),
    (13, "Viluppuram", "Tamil Nadu", "SC"),
    (14, "Kallakurichi", "Tamil Nadu", "GEN"),
    (15, "Salem", "Tamil Nadu", "GEN"),
    (16, "Namakkal", "Tamil Nadu", "GEN"),
    (17, "Erode", "Tamil Nadu", "GEN"),
    (18, "Tiruppur", "Tamil Nadu", "GEN"),
    (19, "Nilgiris", "Tamil Nadu", "SC"),
    (20, "Coimbatore", "Tamil Nadu", "GEN"),
    (21, "Pollachi", "Tamil Nadu", "GEN"),
    (22, "Dindigul", "Tamil Nadu", "GEN"),
    (23, "Karur", "Tamil Nadu", "GEN"),
    (24, "Tiruchirappalli", "Tamil Nadu", "GEN"),
    (25, "Perambalur", "Tamil Nadu", "GEN"),
    (26, "Cuddalore", "Tamil Nadu", "GEN"),
    (27, "Chidambaram", "Tamil Nadu", "SC"),
    (28, "Mayiladuthurai", "Tamil Nadu", "GEN"),
    (29, "Nagapattinam", "Tamil Nadu", "SC"),
    (30, "Thanjavur", "Tamil Nadu", "GEN"),
    (31, "Sivaganga", "Tamil Nadu", "GEN"),
    (32, "Madurai", "Tamil Nadu", "GEN"),
    (33, "Theni", "Tamil Nadu", "GEN"),
    (34, "Virudhunagar", "Tamil Nadu", "GEN"),
    (35, "Ramanathapuram", "Tamil Nadu", "GEN"),
    (36, "Thoothukkudi", "Tamil Nadu", "GEN"),
    (37, "Tenkasi", "Tamil Nadu", "SC"),
    (38, "Tirunelveli", "Tamil Nadu", "GEN"),
    (39, "Kanniyakumari", "Tamil Nadu", "GEN"),
    # Puducherry (1)
    (40, "Puducherry", "Puducherry", "GEN"),
    # Key National Constituencies for Lok Sabha
    (41, "Varanasi", "Uttar Pradesh", "GEN"),
    (42, "New Delhi", "Delhi (NCT)", "GEN"),
    (43, "Wayanad", "Kerala", "GEN"),
    (44, "Bangalore South", "Karnataka", "GEN"),
    (45, "Mumbai South", "Maharashtra", "GEN"),
    (46, "Gandhinagar", "Gujarat", "GEN"),
    (47, "Hyderabad", "Telangana", "GEN"),
    (48, "Baramati", "Maharashtra", "GEN"),
    (49, "Lucknow", "Uttar Pradesh", "GEN"),
    (50, "Diamond Harbour", "West Bengal", "GEN"),
]

# Political Parties with symbols, abbreviations, colors
POLITICAL_PARTIES = [
    {
        "name": "Dravida Munnetra Kazhagam",
        "abbreviation": "DMK",
        "symbol": "Rising Sun",
        "color": "#E53935",
        "logo_url": "https://images.unsplash.com/photo-1544717305-2782549b5136?auto=format&fit=crop&q=80&w=200",
        "description": "Major regional political party in Tamil Nadu founded by C. N. Annadurai in 1949."
    },
    {
        "name": "All India Anna Dravida Munnetra Kazhagam",
        "abbreviation": "AIADMK",
        "symbol": "Two Leaves",
        "color": "#2E7D32",
        "logo_url": "https://images.unsplash.com/photo-1532375810709-75b1da00537c?auto=format&fit=crop&q=80&w=200",
        "description": "Major regional political party founded by M. G. Ramachandran in 1972."
    },
    {
        "name": "Bharatiya Janata Party",
        "abbreviation": "BJP",
        "symbol": "Lotus",
        "color": "#FF9933",
        "logo_url": "https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?auto=format&fit=crop&q=80&w=200",
        "description": "Major national political party in India, founded in 1980."
    },
    {
        "name": "Indian National Congress",
        "abbreviation": "INC",
        "symbol": "Hand",
        "color": "#19AAED",
        "logo_url": "https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&q=80&w=200",
        "description": "Historic national political party in India, founded in 1885."
    },
    {
        "name": "Naam Tamilar Katchi",
        "abbreviation": "NTK",
        "symbol": "Microphone",
        "color": "#FBC02D",
        "logo_url": "https://images.unsplash.com/photo-1589829545856-d10d557cf95f?auto=format&fit=crop&q=80&w=200",
        "description": "Tamil nationalist political party in Tamil Nadu led by Seeman."
    },
    {
        "name": "Pattali Makkal Katchi",
        "abbreviation": "PMK",
        "symbol": "Mango",
        "color": "#F57C00",
        "logo_url": "https://images.unsplash.com/photo-1590779033100-9f60a05a013d?auto=format&fit=crop&q=80&w=200",
        "description": "Regional social democratic party in northern Tamil Nadu."
    },
    {
        "name": "Tamilaga Vettri Kazhagam",
        "abbreviation": "TVK",
        "symbol": "Whistle",
        "color": "#8E24AA",
        "logo_url": "/images/parties/tvk_flag.png",
        "description": "Political party founded in 2024 by Vijay championing secular social democracy."
    },
    {
        "name": "Desiya Murpokku Dravida Kazhagam",
        "abbreviation": "DMDK",
        "symbol": "Murasu (Drum)",
        "color": "#D32F2F",
        "logo_url": "https://images.unsplash.com/photo-1519892300165-cb5542fb47c7?auto=format&fit=crop&q=80&w=200",
        "description": "Regional political party founded in 2005 by Captain Vijayakant."
    },
    {
        "name": "Communist Party of India (Marxist)",
        "abbreviation": "CPI(M)",
        "symbol": "Hammer and Sickle",
        "color": "#C62828",
        "logo_url": "https://images.unsplash.com/photo-1541872703-74c5e44368f9?auto=format&fit=crop&q=80&w=200",
        "description": "Left-wing national communist party."
    },
    {
        "name": "Communist Party of India",
        "abbreviation": "CPI",
        "symbol": "Ears of Corn and Sickle",
        "color": "#B71C1C",
        "logo_url": "https://images.unsplash.com/photo-1541872703-74c5e44368f9?auto=format&fit=crop&q=80&w=200",
        "description": "Oldest communist political party in India."
    },
    {
        "name": "Viduthalai Chiruthaigal Katchi",
        "abbreviation": "VCK",
        "symbol": "Pot",
        "color": "#00838F",
        "logo_url": "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&q=80&w=200",
        "description": "Social justice and anti-caste movement led by Thol. Thirumavalavan."
    },
    {
        "name": "Aam Aadmi Party",
        "abbreviation": "AAP",
        "symbol": "Broom",
        "color": "#00796B",
        "logo_url": "https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?auto=format&fit=crop&q=80&w=200",
        "description": "National party founded on anti-corruption and public service delivery."
    },
    {
        "name": "Indian Union Muslim League",
        "abbreviation": "IUML",
        "symbol": "Ladder",
        "color": "#006600",
        "logo_url": "https://images.unsplash.com/photo-1544717305-2782549b5136?auto=format&fit=crop&q=80&w=200",
        "description": "Historical regional ally and recognized political party in Tamil Nadu."
    },
    {
        "name": "Amma Makkal Munnettra Kazhagam",
        "abbreviation": "AMMK",
        "symbol": "Pressure Cooker",
        "color": "#D81B60",
        "logo_url": "https://images.unsplash.com/photo-1532375810709-75b1da00537c?auto=format&fit=crop&q=80&w=200",
        "description": "Regional political party founded in 2018 by T. T. V. Dhinakaran."
    },
    {
        "name": "Independent",
        "abbreviation": "IND",
        "symbol": "Free Symbol (Ring/Kite)",
        "color": "#9E9E9E",
        "logo_url": "https://images.unsplash.com/photo-1577495508048-b635879837f1?auto=format&fit=crop&q=80&w=200",
        "description": "Non-affiliated citizen candidate."
    },
    {
        "name": "None of the Above",
        "abbreviation": "NOTA",
        "symbol": "Ballot Cross",
        "color": "#546E7A",
        "logo_url": "https://images.unsplash.com/photo-1540910419892-4a36d2c3266c?auto=format&fit=crop&q=80&w=200",
        "description": "Right of the elector to express dissatisfaction with all contesting candidates."
    }
]

# Official 2026 Tamil Nadu Legislative Assembly Election Results Dataset (ECI Reference)
# Total Seats: 234. Single Majority Mark: 118.
OFFICIAL_2026_TN_ASSEMBLY_RESULTS = {
    "election_name": "Tamil Nadu Legislative Assembly Election 2026",
    "state": "Tamil Nadu",
    "country": "India",
    "election_type": "Legislative Assembly",
    "total_constituencies": 234,
    "majority_mark": 118,
    "polling_date": "2026-04-23",
    "counting_date": "2026-05-04",
    "status": "COMPLETED",
    "source": "Election Commission of India",
    "source_url": "https://results.eci.gov.in",
    "retrieved_at": "2026-05-04T18:00:00Z",
    "is_demo_data": True,
    "disclaimer": "Official historical election data provided for educational simulation. Not affiliated with the Election Commission of India.",
    "parties_seat_distribution": [
        {"party": "TVK", "party_name": "Tamilaga Vettri Kazhagam", "symbol": "Whistle", "seats": 108, "seat_pct": 46.15, "color": "#8E24AA", "alliance": "TVK Alliance"},
        {"party": "DMK", "party_name": "Dravida Munnetra Kazhagam", "symbol": "Rising Sun", "seats": 59, "seat_pct": 25.21, "color": "#E53935", "alliance": "SPA / INDIA"},
        {"party": "ADMK", "party_name": "All India Anna Dravida Munnetra Kazhagam", "symbol": "Two Leaves", "seats": 47, "seat_pct": 20.09, "color": "#2E7D32", "alliance": "AIADMK Alliance"},
        {"party": "INC", "party_name": "Indian National Congress", "symbol": "Hand", "seats": 5, "seat_pct": 2.14, "color": "#19AAED", "alliance": "SPA / INDIA"},
        {"party": "PMK", "party_name": "Pattali Makkal Katchi", "symbol": "Mango", "seats": 4, "seat_pct": 1.71, "color": "#F57C00", "alliance": "NDA"},
        {"party": "IUML", "party_name": "Indian Union Muslim League", "symbol": "Ladder", "seats": 2, "seat_pct": 0.85, "color": "#006600", "alliance": "SPA / INDIA"},
        {"party": "CPI", "party_name": "Communist Party of India", "symbol": "Ears of Corn and Sickle", "seats": 2, "seat_pct": 0.85, "color": "#B71C1C", "alliance": "SPA / INDIA"},
        {"party": "VCK", "party_name": "Viduthalai Chiruthaigal Katchi", "symbol": "Pot", "seats": 2, "seat_pct": 0.85, "color": "#00838F", "alliance": "SPA / INDIA"},
        {"party": "CPI(M)", "party_name": "Communist Party of India (Marxist)", "symbol": "Hammer and Sickle", "seats": 2, "seat_pct": 0.85, "color": "#C62828", "alliance": "SPA / INDIA"},
        {"party": "BJP", "party_name": "Bharatiya Janata Party", "symbol": "Lotus", "seats": 1, "seat_pct": 0.43, "color": "#FF9933", "alliance": "NDA"},
        {"party": "DMDK", "party_name": "Desiya Murpokku Dravida Kazhagam", "symbol": "Murasu (Drum)", "seats": 1, "seat_pct": 0.43, "color": "#D32F2F", "alliance": "AIADMK Alliance"},
        {"party": "AMMK", "party_name": "Amma Makkal Munnettra Kazhagam", "symbol": "Pressure Cooker", "seats": 1, "seat_pct": 0.43, "color": "#D81B60", "alliance": "Independent Alliance"}
    ]
}

